name: Check image defined by dockerfile

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pbuild
#         run: docker build . --file Dockerfile --tag berezun/test:latest
        run: docker build . --file Dockerfile --tag berezun/cw-2020:latest
      - name: Log into registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push image
#         run: docker push berezun/test:latest
        run: docker push berezun/cw-2020:latest

