name: Trololo

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update --fix-missing
        sudo apt-get install gcc-multilib
    - name: Install  opam
      run: |
        sudo add-apt-repository ppa:avsm/ppa
        sudo apt update
        sudo apt install opam
    - name: opam init
      run: opam init -y
    - name: install ocaml
      run: |
        eval `opam env`
        opam switch create 4.07.1
        eval `opam env`
    - name: install ostap
      run: opam pin add -y ostap https://github.com/dboulytchev/ostap.git#memoCPS
    - name: install lama
      run: opam pin add -y lama https://github.com/JetBrains-Research/Lama.git
    - name: check
      run: |
        eval `opam env`
        opam pin list
        lamac -v
