name: Build Hello World executable
on: [push, pull_request]
jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0
      - run: apt-get install opam
      - run: opam pin add -n ostap https://github.com/dboulytchev/ostap.git#memoCPS
      - run: opam pin add -y lama https://github.com/JetBrains-Research/Lama.git
      - run: opam pin list
      - run: lamac -v
